##### Macros #####
MACRO(SUBDIRLIST result curdir)
    FILE(GLOB children RELATIVE ${curdir} ${curdir}/*)
    SET(dirlist "")
    FOREACH(child ${children})
        IF(IS_DIRECTORY ${curdir}/${child})
            LIST(APPEND dirlist ${child})
        ENDIF()
    ENDFOREACH()
    SET(${result} ${dirlist})
ENDMACRO()

#### Functions #####
function(LOAD_CMAKEFILES_IN_DIR dirName)
    message("++ Loading all CMake files in the dir: ${dirName}")
    file(GLOB cmakeFiles ${dirName}/*/CMakeLists.txt)
    foreach(cmakeFile ${cmakeFiles})
        message("++ Including: ${cmakeFile}")
        INCLUDE(${cmakeFile})
    endforeach(cmakeFile)
endfunction(LOAD_CMAKEFILES_IN_DIR)

function(ADD_DIRS_IN_DIR dirName)
    SUBDIRLIST("SUBDIRS" ${dirName})
    foreach(subdir ${SUBDIRS})
        add_subdirectory(${subdir})
    endforeach(subdir)
endfunction(ADD_DIRS_IN_DIR)